### ISSUE TITLE
[Feature] more use of the inline keyword

### ISSUE THREAD

**Issue by ghost** [PDeveloper/hxE#1]
I noticed that nearly no function is inlined. Did you experienced any problems with that or does it have another reason?

btw nice lib :)

**Comment by PDeveloper** [comment]
I'll definitely update this library soon, and see where it would be appropriate to use inline! Thanks! :)

**Comment by ghost** [comment]
wow thanks for the quick response :)

**Comment by PDeveloper** [comment]
Finally got around to it :)
Any functions that were simply forwarding their call I inlined in the Entity and EntityWorld classes, which were the biggest issues as I see. Any further optimizations can be PRed.

35e2697a2eb655aaa6712680be13c4ba75b361b0
