### ISSUE TITLE
Child/Parent entities

### ISSUE THREAD

**Issue by Partysun** [PDeveloper/hxE#2]
What do you think about add child link and parent link properties for entity?

**Comment by PDeveloper** [comment]
What would be the use case? Children and parents should be linked through a ChildOfComponent that is attached to child entities.

But please write what you were thinking/the use case you have! :)

**Comment by Partysun** [comment]
@PDeveloper Yes, chilldComponent makes my problem very well. I think it's very basic pattern of the ecs framework, but it's not big problem.
@PDeveloper Why hxE doesn't have get by ids or tags methods? For example, I want to get 5 entities for make AI decision. I can store this id like an array in components, but it's not very well. What is the best practice to do this?

**Comment by PDeveloper** [comment]
Like mentioned in the PR, what do you want to achieve using tags? This should be done through components, in your case:
TeamComponent which just holds an enum like { RED; BLUE; GREEN; };
Then a System processes this components and keeps track of how many entities from each team. Then in AI, you check the currently processing entity's TeamComponent, and you can then check all entities that aren't of the same team colour.

Something like that should give you the "proper" and most flexible approach from what I understand. Tags can be added either way as an easier approach I guess, I can add this very quickly using the same interface as in your PR, with a few added improvements.

**Comment by PDeveloper** [comment]
Latest commit adds support for tags. You can use it like you had in your PR, except you can also access all entities by a tag from the EntityWorld class as well.

35e2697a2eb655aaa6712680be13c4ba75b361b0
